trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'nodewebapp'
  skipComponentGovernanceDetection: 'true' # Disable internal to Microsoft injected policy to save some time in the build

steps:
- task: Docker@2
  displayName: Build and push image to Azure Container Registry
  inputs:
    containerRegistry: 'gjadacr'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'