trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-javascript-docker'
  skipComponentGovernanceDetection: 'true' # Disable internal to Microsoft injected policy to save some time in the build

steps:
#- task: Docker@2
#  displayName: Build image
#  inputs:
#    repository: $(imageName)
#    command: build
#    Dockerfile: app/Dockerfile
- task: Docker@2
  displayName: Build and push image to Azure Container Registry
  inputs:
    containerRegistry: 'AzureContainerRegistry'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'