apiVersion : apps/v1
kind: Deployment
metadata:
  name: nodewebapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodewebapp
  template:
    metadata:
      labels:
        app: nodewebapp 
    spec:
      containers:
        - name: nodewebapp 
          image: gjadacr.azurecr.io/nodewebapp
          ports:
          - containerPort: 8080